lab4/FurnitureFactory/FAQ/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq, name='faq_list'),
]

lab4/FurnitureFactory/FurnitureFactory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('cart/',
         include('cart.urls', namespace='cart')),
    path('statistic/',
         include('statistic.urls', namespace='statistic')),
    path('apistuff/',
         include('apistuff.urls', namespace='apistuff')),

    path('comments/',
         include('comments.urls', namespace="comments")),
    path('news/',
         include('articles.urls', namespace="articles")),
    path('faq/', include('FAQ.urls', namespace='faq')),
    path('promo/', include('promo.urls', namespace='promo')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    path('order/',
         include('order.urls', namespace='orders')),

    path('auth/',
         include('login.urls', namespace='login')),
    path('',
         include('factory.urls', namespace='factory')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab4/FurnitureFactory/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

lab4/FurnitureFactory/factory/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     path('about/', views.about),
     path('lab3/', views.lab3),
     path('contacts/', views.contacts),
     path('main/', views.guest),
     path('privacy_policy/', views.privacy_policy),
     path('<int:id>', views.product_detail, name='product_detail'),
     path("create/", views.product_create),
     path("edit/<int:id>/", views.product_edit),
     path("delete/<int:id>/", views.product_delete),
     path('<str:product_type_name>/', views.product_list, name='product_list_by_category')]

lab4/FurnitureFactory/login/urls.py
from . import views
from django.urls import path

app_name = 'login'

urlpatterns = [

    path('logout/',
         views.LogOutView.as_view(),
         name='logout'),
path('login/',
         views.LoginFormView.as_view(),
         name='login'),
    path('signup/',
         views.SignUpFormView.as_view(),
         name='signup')
]

lab4/FurnitureFactory/factory/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class FurnitureCategory(models.Model):
    category = models.CharField(max_length=25, help_text='Category of Furniture')

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[str(self.category)])

    def __str__(self):
        return self.category


class FurnitureCollection(models.Model):
    collection = models.CharField(max_length=25, help_text='Collection to that item belongs')

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[str(self.collection)])

    def __str__(self):
        return self.collection


class Furniture(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    code = models.CharField(max_length=8)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.CharField(max_length=1000)
    category = models.ForeignKey(FurnitureCategory, on_delete=models.SET_NULL, null=True)
    collection = models.ForeignKey(FurnitureCollection, on_delete=models.SET_NULL, null=True)
    purchase_count = models.PositiveIntegerField(default=0)
    quantity = models.IntegerField()
    PRODUCTION_STATUS = (
        ('p', 'Produced'),
        ('s', 'Stopped')
    )

    attributes = models.CharField(max_length=2,
                                  choices=PRODUCTION_STATUS,
                                  help_text="state of production")

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Client(models.Model):
    """
    module for client
    """
    first_name = models.CharField(max_length=200,
                                  help_text='Name')
    last_name = models.CharField(max_length=200,
                                 help_text='Surname')
    birth_date = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=19,
                             help_text='Phone Number')
    city = models.CharField(max_length=50,
                            help_text='City')
    address = models.CharField(max_length=200,
                              help_text='Street, Building, etc')
    image = models.ImageField(upload_to='user/%Y/%m/%d', default='static/images/mi_safe.png', null=True)

    def get_absolute_url(self):
        return reverse('client-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}, {2}'.format(self.first_name, self.last_name, self.city)

lab4/FurnitureFactory/factory/forms.py
from django import forms

from .models import Furniture


class ProductForm(forms.ModelForm):
    class Meta:
        model = Furniture
        fields = ['name', 'price', 'code', 'image', 'description', 'category', 'collection', 'attributes']

lab4/FurnitureFactory/factory/views.py
from django.shortcuts import render, get_object_or_404
from .models import Furniture, FurnitureCategory, FurnitureCollection
from cart.forms import CartAddProductForm
from django.http import HttpResponseRedirect, HttpResponseNotFound
from .forms import ProductForm
from django.core.exceptions import PermissionDenied
from login.models import ClientUser
from articles.models import Article
import requests




def product_list(request, product_type_name=None):
    product_type = None
    types = FurnitureCategory.objects.all()
    products = Furniture.objects.all()

    if product_type_name:
        product_type = get_object_or_404(FurnitureCategory, category=product_type_name)
        products = products.filter(category=product_type)

    sort = request.GET.get('sort')
    if sort == 'ascending':
        products = products.order_by('price')
    elif sort == 'descending':
        products = products.order_by('-price')

    return render(request, 'factory/product/list.html',
                  {
                      'type': type,
                      'types': types,
                      'products': products,
                  })

def product_list_collection(request, product_collection_name=None):
    product_type = None
    types = FurnitureCollection.objects.all()
    products = Furniture.objects.all()

    if product_collection_name:
        product_collection = get_object_or_404(FurnitureCollection, collection=product_collection_name)
        products = products.filter(collection=product_collection)

    sort = request.GET.get('sort')
    if sort == 'ascending':
        products = products.order_by('price')
    elif sort == 'descending':
        products = products.order_by('-price')

    return render(request, 'factory/product/list.html',
                  {
                      'type': type,
                      'types': types,
                      'products': products,
                  })


def product_detail(request, id):
    product = get_object_or_404(Furniture, id=id)
    cart_product_form = CartAddProductForm()


    return render(request, 'factory/product/detail.html', {'product': product,
                                                         'cart_product_form': cart_product_form})
#


def product_create(request):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    form = ProductForm()

    if request.method == "POST":

        product = Furniture.objects.create(name=request.POST.get('name'),
                                           price=request.POST.get('price'),
                                           code=request.POST.get('code'),
                                           image=request.FILES.get('image'),
                                           description=request.POST.get('description'),
                                           category=FurnitureCategory.objects.get(id=request.POST.get('category')),
                                           collection=FurnitureCollection.objects.get(id=request.POST.get('collection')),
                                           quantity=0,
                                           attributes=request.POST.get('attributes'))

        product.save()
        return HttpResponseRedirect("/")
    else:
        return render(request, "factory/product/create.html", {"form": form})


def product_edit(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    try:

        product = Furniture.objects.get(id=id)
        form = ProductForm(initial={'name': product.name, 'price': product.price, 'code': product.code,
                                    'image': product.image, 'category': product.category,
                                    'collection': product.collection, 'description': product.description,
                                    'attributes': product.attributes})

        if request.method == "POST":
            product.name = request.POST.get('name')
            product.price = request.POST.get('price')
            product.category = Furniture.objects.get(id=request.POST.get('category'))
            product.collection = FurnitureCategory.objects.get(id=request.POST.get('collection'))
            product.image = request.FILES.get('image')
            product.description = request.POST.get('description')

            product.attributes = request.POST.get('attributes')

            product.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "factory/product/edit.html", {"product": product, "form": form})
    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>product not found</h2>")


def product_delete(request, id):
    """
    deleting data in estate base
    """
    if not request.user.is_staff:
        raise PermissionDenied("You do not have access to this page.")

    try:

        product = Furniture.objects.get(id=id)
        product.delete()
        return HttpResponseRedirect("/")
    except product.DoesNotExist:
        return HttpResponseNotFound("<h2>Product not found</h2>")


def about(request):
    return render(request, 'templateslab1/about_company.html')
def lab3(request):
    return render(request, 'templateslab1/lab3.html')


def contacts(request):

    staff = ClientUser.objects.filter(is_staff=True)
    context = {'staff': staff}
    for member in staff:
        print(member.image)

    return render(request, 'templateslab1/contacts.html', context)


def guest(request):
    article = Article.objects.all().order_by('-created')[0]
    return render(request, 'templateslab1/guest_page.html', {'article':article})


def privacy_policy(request):
    return render(request, 'templateslab1/privacy_policy.html')

lab4/FurnitureFactory/factory/templates/factory/homepage.html
<!DOCTYPE html>

<html>
 <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
        overflow: hidden;
      }
      body {
        overflow: auto; /* добавить полосу прокрутки */
      }
      main {
        min-height: 90%;
      }

      </style>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}Furniture Factory{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/homepage.css" type="text/css">
    <link rel="shortcut icon" href="/static/images/icon.ico" type="image/x-icon">

    <style>

    </style>
</head>
<body>

<header>
    <div class="headernav" style="height: 100%;">
        <a href="/" class="logo">
            <img width="75" src="/static/images/logo.png"/>
        </a>
        <a href="/apistuff/">Lucky Page</a>
        <a href="/main/">new</a>
        {% if user.is_superuser %}
        <a href="/statistic/">Statistic</a>
        {% endif %}
    </div>


</header>
<main>
    <div class="maincontent">
    <div id="subheader" >
        <div class="cart" >
            {% if user.is_authenticated and not user.is_superuser%}
            {% with total_items=cart|length %}
            {% if cart|length > 0 %}
            In cart:
            <a class="button4" href="{% url 'cart:detail' %}">{{ total_items }} pcs, {{ cart.get_total_price }}</a>
            {% else %}
            Cart empty
            {% endif %}
            {% endwith %}
            {% endif %}
        </div>
        <div class="time">
            <span>Today: <span id='date'></span></span>
            <span>Last reload: <span id='time'></span></span>

        </div>
        </div>
        <div class="login" >
            {% if user.is_authenticated %}
            | {{ user.username }} |
            <a class="button4" href="{% url 'login:logout' %}">Log out</a>
            {% else %}
            <a class="button4" href="{% url 'login:login' %}">Sign in</a>
            <a class="button4" href="{% url 'login:signup' %}">Sign up</a>
            {% endif %}
        </div>
    </div>
    <div style="margin-top: -100px;">
   {% block content %}{% endblock %}
    </div>
    </div>
</main>

    <script>
        const today = new Date();
        const year = today.getFullYear();
        let month = today.getMonth() + 1; // Months start at 0!
        let day = today.getDate();
        let hour = today.getHours();
        let min = today.getMinutes();
         let sec = today.getSeconds();
        if (hour < 10)
            hour = '0' + hour;
        if (min < 10)
            min = '0' + min;
        if (sec < 10)
            sec = '0' + sec;
        if (day  < 10) day  = '0' + day ;
        if ( month < 10)  month = '0' +  month;

        let date_str = day + '-' + month + '-' + year;
        let time = hour + ":" + min + ":" + sec;
        let tz = -(new Date().getTimezoneOffset() / 60);
        if (tz > 0) {
            tz = "+" + tz;
        }
        else if (tz < 0) {
            tz = "-" + tz;
        }
        tz = "UTC" + tz;
        time = time + "   (" + tz + ")"

        document.getElementById('date').innerHTML = date_str;
        document.getElementById('time').innerHTML = time;
        document.getElementById('zone').innerHTML = tz;
    </script>

<div class="footer">
        <p style="color: rgb(100, 0, 140);">&copy; 2023 Feel like a king with our love and furniture.</p>
    </div>
</body>
 <script src="/static/js/age.js" defer></script>
<script src="/static/js/cardanim.js" defer></script>

</html>