lab4/FurnitureFactory/FAQ/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.faq, name='faq_list'),
]

lab4/FurnitureFactory/FurnitureFactory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('cart/',
         include('cart.urls', namespace='cart')),
    path('statistic/',
         include('statistic.urls', namespace='statistic')),
    path('apistuff/',
         include('apistuff.urls', namespace='apistuff')),

    path('comments/',
         include('comments.urls', namespace="comments")),
    path('news/',
         include('articles.urls', namespace="articles")),
    path('faq/', include('FAQ.urls', namespace='faq')),
    path('promo/', include('promo.urls', namespace='promo')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    path('order/',
         include('order.urls', namespace='orders')),

    path('auth/',
         include('login.urls', namespace='login')),
    path('',
         include('factory.urls', namespace='factory')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab4/FurnitureFactory/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

lab4/FurnitureFactory/factory/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     path('about/', views.about),
     path('lab3/', views.lab3),
     path('contacts/', views.contacts),
     path('main/', views.guest),
     path('privacy_policy/', views.privacy_policy),
     path('<int:id>', views.product_detail, name='product_detail'),
     path("create/", views.product_create),
     path("edit/<int:id>/", views.product_edit),
     path("delete/<int:id>/", views.product_delete),
     path('<str:product_type_name>/', views.product_list, name='product_list_by_category')]

lab4/FurnitureFactory/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('create/',
         views.order_create,
         name='order_create'),
]

lab4/FurnitureFactory/cart/models.py
from django.db import models

# Create your models here.

lab4/FurnitureFactory/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 15)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

lab4/FurnitureFactory/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from factory.models import Furniture
from .cart import Cart
from .forms import CartAddProductForm
from django.core.exceptions import PermissionDenied


@require_POST
def cart_add(request, product_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    product = get_object_or_404(Furniture, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('/')


def cart_remove(request, product_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    product = get_object_or_404(Furniture, id=product_id)
    cart.remove(product)
    return redirect('/')


def cart_detail(request):
    if not request.user.is_authenticated :
        raise PermissionDenied("You do not have access to this page.")

    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

lab4/FurnitureFactory/cart/templates/cart/detail.html
{% extends "factory/homepage.html" %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
{% endblock %}

{% block title %}
  Shopping Cart
{% endblock %}

{% block content %}
<h1 class="cart-heading">Shopping Cart</h1>
<div class="cart-container">
    <table class="cart-table" border="1">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Amount</th>
          <th>Code</th>
          <th>Total Price</th>
          <th>Update Quantity</th>
          <th>Remove</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart %}
          {% with product=item.product %}
            <tr>
              <td class="cart-image">
                <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'images/mi_safe.png' %}{% endif %}" class="product-image">
                </a>
              </td>
              <td>{{ product.name }}</td>
              <td>{{ item.quantity }}</td>
              <td>{{ item.code }}</td>
              <td class="cart-price">{{ item.total_price }}</td>
              <td class="cart-update">
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}
                  <button type="submit" class="btn-update">Save</button>
                  {% csrf_token %}
                </form>
              </td>
              <td class="cart-remove"><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
            </tr>
          {% endwith %}
        {% endfor %}
        <tr class="cart-total">
          <td colspan="4"></td>
          <td colspan="2">Total:</td>
          <td class="cart-price">{{ cart.get_total_price }}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="cart-buttons">
    <a href="{% url 'store:product_list' %}" class="button4">Continue Shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button4">Checkout</a>
  </div>
</div>
{% endblock %}